repository_type: pipeline

nf_core_version: 3.5.1

lint: {}

template:
  org: nf-core
  name: seia
  description: A nf-core pipeline for super-enhancer identification and annotation
  author: '@asntech'
  version: 1.0.0dev
  force: true
  outdir: .
  is_nfcore: true
