name: rose_to_beds
description: "Convert ROSE stitched enhancer table into SE/TE BEDs and constituent peak BEDs"
keywords:
  - rose
  - super-enhancer
  - enhancer
  - bed
tools:
  - python:
      description: "Python"
      homepage: "https://www.python.org/"
      documentation: "https://docs.python.org/"
input:
  - all_enhancers:
      type: file
      description: "ROSE stitched table (e.g., *_STITCHED_REGION_MAP.txt)"
  - peaks:
      type: file
      description: "Peaks BED file (BED3+)"
output:
  - SEs.bed:
      type: file
      description: "Super-enhancer stitched regions (BED6)"
  - TEs.bed:
      type: file
      description: "Typical enhancer stitched regions (BED6)"
  - SEs_constituents.bed:
      type: file
      description: "Peaks overlapping SE stitched regions"
  - TEs_constituents.bed:
      type: file
      description: "Peaks overlapping TE stitched regions"
authors:
  - "Aziz Khan"
